### ISSUE TITLE
ScaffCC does not compile with C++11

### ISSUE THREAD

**Issue by amrutn** [epiqc/ScaffCC#37]
When trying to compile with C++11 on ubuntu 18.0.4, G++ 7.4.0 and cmake 3.13.3, there is an error at the following stage, 

llvm[3]: Compiling ToolRunner.cpp for Release+Asserts build
/home/project/ScaffCC/llvm/tools/bugpoint/ToolRunner.cpp:131:12: error: invalid operands to
      binary expression ('llvm::raw_ostream' and 'std::ostringstream' (aka
      'basic_ostringstream<char>'))
    errs() << OS;

A potential fix might be found here https://stackoverflow.com/questions/18448846/c11-invalid-operands-to-binary-expression-ostream-and-ostringstream
