### PR TITLE
Segmentation Faults and Fixes to Run main branch on macOS

### LINKED ISSUE #32: Can't find math.h and other headers
I'm using OSX.  I've tried tracking this down, but have spent way too much time trying to figure out where the pre-processor is called, and how to resolve this.

Unitive-MacBook-Pro-1598:scaffcc gonzo$ ./scaffold.sh Algorithms/Binary_Welded_Tree/binary_welded_tree.n100s100.scaffold
Algorithms/Binary_Welded_Tree/binary_welded_tree.n100s100.scaffold
[Scaffold.makefile] Compiling binary_welded_tree.n100s100_merged.scaffold ...
binary_welded_tree.n100s100_merged.scaffold:14:10: fatal error: 'math.h' file not found
#include <math.h>
         ^
1 error generated.
make: *** [binary_welded_tree.n100s100.ll] Error 1

I assume the standard C++ headers are used.  If that's true, these are installed and used in my C++ code.  For the record, I can go to the scripts dir and run regression_tests.sh.  12 of 20 run fine... only the ones requiring headers math.h or stdio.h fail.

### LINKED ISSUE #37: ScaffCC does not compile with C++11
When trying to compile with C++11 on ubuntu 18.0.4, G++ 7.4.0 and cmake 3.13.3, there is an error at the following stage, 

llvm[3]: Compiling ToolRunner.cpp for Release+Asserts build
/home/project/ScaffCC/llvm/tools/bugpoint/ToolRunner.cpp:131:12: error: invalid operands to
      binary expression ('llvm::raw_ostream' and 'std::ostringstream' (aka
      'basic_ostringstream<char>'))
    errs() << OS;

A potential fix might be found here https://stackoverflow.com/questions/18448846/c11-invalid-operands-to-binary-expression-ostream-and-ostringstream

### PR DESCRIPTION
**Pull request by AndrewLitteken**
Fixes Included:
- Changes to `CFG.h` to work around a more restrictive Xcode toolchain
- Main Makefile now uses the environmental variable `ENABLE_LIBCPP=1` for macOS Builds since the 32-bit version is now deprecated in macOS Sierra onwards (10.12+)
- Fix in `llvm/Makefile.rules` to fix a bad regex where it would only capture the first digit of the minor version
- Fix in `llvm/projects/sample/autoconf/config.guess` to find the architecture the same way llvm does so the 64-bit libraries are used
- Fix in `llvm/lib/Transforms/Scaffold/ResourceCount.cpp` to actually have the right number of array cells to avoid seg faults upon destruction of object
- Fix in `llvm/lib/Transforms/Scaffold/ResourceCount.cpp` to pass the map by reference rather than copy, avoiding seg faults when looking through the map to find gates
- Fix in `llvm/tools/bugpoint/ToolRunner.cpp` to change `errs() << OS;` to `errs() << OS.str();` as suggested in Issue #37 
- Changes in `scaffold/Scaffold.makefile` to find the SDK automatically so regression tests do not fail because header files cannot be found
- Changes in `scripts/regression_test.sh` to find `Scaffold.dylib` on macOS
- Changes in the example test cases so that a lowercase `z` is used rather than a `Z`

closes #32 closes #37

### CODE REVIEW

**Comment by AndrewLitteken** [comment]
I wanted to also try to fix the `Illegal Instruction: 4` issue that is occurring in RKQC, but I wasn't able to track down why that is happening yet.

**Comment by AndrewLitteken** [comment]
All the tests should pass on both macOS and Ubuntu now!
